<?php

/**
 * @file
 * Contains bic_transactions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bic_transactions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bic_transactions module.
    case 'help.page.bic_transactions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The transactions module for the credit membership system in the TCM BiC site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bic_transactions_theme() {
  return [
    'renew_membership_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
